apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: anna-frontend-subteam
  title: Anna Frontend Subteam
  description: Responsible for maintaining and developing the frontend of Anna
  tags:
    - engineering
    - reactjs
spec:
  type: team
  children: []
  parent: anna-team
  # members:
  #   - geralt
  profile:
    email: anna-frontend-subteam@example.com
    # slack: 
