environment: prod

redis_host: master.anna-prod-elascache-rep-group.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 2
  replicas: 1
    
secret:
  redis_pass: AgAi86NigMz6HJmy+rdB6idLfzpilcxrAecZ0DnmEH+D4JwlanmdfmHVSDvd1yC+34tOK6IJezmhodvGLpGufebzs/dPscE5UHcCOVV65FyGuIuayv/rQhqqjgJSG6iBDKEq3atz5cvAz9ipUeZKcpt05WiNLzIzeAQ/04OwqASsWqJx+frd3VYDT9uyVdHbfxeg41pkABO/D7DxzehiIo6HXGosBO3BDOhKr11F4yITqnglHm8A5z80bsAlku/5BcUUop38AfTko0zljLLkNhmbE4diXBITHy29KrpALx7oQk07+oAl2jl346pAKIyHGmQRb+PjPhDtFIzIZKY8jG+UvigaYBLvQjRJRWyrZgkucCfqkntdWC9IJ2rQ0ZY4WC/B1yK9r7JeMiHfKai9aH0zrUVb0zWPWLL3bDSXXbyrr+H0/flI0/DFdBbq1dIn1ZiY+3jrQMhB5x/cp/FLZRhCwazfdR3HSqNUH7Z12AU6XxUAjD37nYAnJ6hiNZAo21myKRrIqdqnMxcigOxaJubPSRH2Be5weD7ZHRQqsm3XBoIDu1oUUAxPooRNmiYciqtmqnvxtv9eocj2Rirwu7uE/GZZEWhp5eFpRTHbxMZjzi1XkZiBT5hIWARoogn0PKNq68mkPIJJqtvusnj9RIfTLE4CNkR7LCThp+Ag0Rh7CnpSjk4xtk7NXaofDAJ0Nm63nA+sPk/lQKdRWmsZcs4bUaAf6fkcVfT9ZY83 # This value was modified by the sealed-secrets pipeline
