apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
spec:
  encryptedData:
    REDIS_PASS: {{ .Values.github_token }}
  template:
    metadata:
      name: github-token
      namespace: {{ include "common.names.fullname" . }}
    type: Opaque