environment: prod

redis_host: master.anna-prod-elascache-rep-group.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 10
  replicas: 1
    
secret:
  redis_pass: AgAz8h4goNl3E42cjlSlcARQ5M7x9ZmbMep/Zj2DQyLlzeL3KzJZEWDRIwOHwLMkK/y6xAa4OBwlWJb3QMIfTBR7ki/znnIIGfCuUb+lcLW3TYi2yJy3lmK0ZIQvqxjv9FwAUlqPySrocO2wX9ehO6PxN4XyWjCPNjgzYe2VBY7yn6irWRYTP/ZEl//h7Fe4XDn65+jPBELPT1kdkTPh3Uk0jraTnNr8tTj9sK1SEfXzJLsiho6eKUUbwQn4HS3yJvQWsaca2nYxNR1Ii4BbhIOfp82vSDhTlKeCfvzNFJiu5W4qjPpoHzsNJScGdi+HbJmJFEhvVH9zLFVg78PTHyUaBCoQOg1+BGble+iG4eDb/6p1S8Yq7my1ssgVgemTL/imOqkA4bHeyNu/cwBXWHcNwnu2gIeS8Pwzmoj6Qxy2CPqWhCLMGUnFJmmlfCQzNzMBNW+vWoU9K+jxMgb/Pa/d3Hzi7YEisTlUkzsIkzIum0KBt82zpO2FZxDZCH+1wRwn7kJ7tm36hy+7c8YaquJPVYik3W8+L/pIYB/lWI7dxlH8sLMq0H+aPbfI+kVgQV+oWs4PSnRREGZoDPG+/naaLTZXJwcKho/9gPdhcLJLUor8HZYM0nPch0gw/UDM0THvzRJ02nx6vnzPtge01dsgemJLiKQE11g6/fSb2nuJ696rsSWiy5hzlxu72dirNSiGzN6fdWDOEiazMDLQ5rOQtrrbP5VYH/AVk0Uq1BsR9kmD7f3j1Z8XJMg1Rvfru4U= # This value was modified by the sealed-secrets pipeline
