environment: stage

redis_host: master.anna-stage-elascache-rep-group.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 10
  replicas: 1

secret:
  redis_pass: AgClUANKNug34IdHeUaaBW7WEZcQeywbUe3uYzCiJjQ3ljCbjY94Chi9BIUc6AxVkl8W+SSTs6M5+xG6DCB+wu22ZLbM3mkJK25TVflPOPLT7XBzPPhD/A4NOp0mvgC4A1Fbre2Kzp77/d9Tv3hDoiTSbH+gIoeudGvVEG7Ce/2Sa6wfRaJrQIexZkyz6r/ckAtikzp3eXqXVccgL1EMq06fUUxmIhmqEqATOFvH+NYSML5c0oykNGB7zJDCzoEncxCUr5hY4tXN4BN5MzU5UO8hfvIstVeGvAtoxAe575T/qZFsiwlaav2Ex8kqXsOiRpoeGGsCk1CJ8bIdWK2+U99eKLDVrF9QVAjkJI3/vq30+TZng9nMEVNTPqHT5qdkWUA5OLvulK3d1n0ym+0pBSY5gAq1QmxC0tRC0M/l19jVnMfKxvK3ZLihWSQ+mg+w/VPAX36j6uyv3l/ubMIhP57p7cAtPUEdxKg8F2i2h5gpBqZZTDzcC8nM/53mQUj2zXefB/m01kNfI0Evzc8KOVKiRLwBS3d8cjZya6LF7VXy2DgDPSFAPm9/NzpzKkYcR/dAxe7/cfiSnOVsSDLeqpS/1OP0p0VRMSOVOy1M923FrKLxuCQsxG5Z7aqM1aaz3wlyxYcEc91n7BsPb6eY24gCnoVVaCgbN0WMm4RELYnmGQepmwVTO820d1PLQ99FixdkfwCg3BhBWqd5gNDJFrqEFPQ2xQioCphZupVP302PTJocl+4MP44OCq96za7RQ0YT # This value was modified by the sealed-secrets pipeline
