environment: stage

redis_host: master.anna-stage-elascache-rep-group.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 7
  replicas: 1

secret:
  redis_pass: AgBoCN9flCx32MEdsvr8JmvW6Dr481BSS9ADDT6Ww2rvesRq/nWBWJFkEaN+YmCIHHHzH9lE+5GgISMRJGzEGLSx8c58UFhhCwLx6vzKcX1irOysh1itJGSTCtxXmtYXeWLmWwmURJSZWQDBUoMWmn3gJiwT4+4W19Ghc3QN3HbLYUCn+whoGzADjSXOZ3c20fuACukHoQvpyGbw2EC4Hk3G/hypWG8OGlHHn/acGKIN2oE68WnzV2rhW7XtJnLAuxqEkFrRM4HiUqLeABUkS4Lvsu9wfhVcVZtZFwwW6X75lPEB/9agNuUN93jG05EooA5Vd+hLVcOaMJWxUTc1RKv7fcOCwaS+sEu2ClfsRXqDxwC8EujsKXvNSGOCcSTn2WlJmxrZPzgmRJY52CQ/u0nKPRmxN7mLluevcuOFO2dasoxoPI035EDmMlUmsysrbiRWK12EE7Ae5BiP3XUaQNOsMup/2suf4huEkNmOPQkY9gOvR0BKNURWFbX6/5/8lGtdOkD5zVFmCfBbwkXr99FnOwx9EfPxzhwI0xR+ZyIkT43YB/GvIWYp7N1ze29KD0wn0/Gc3rtO8g9Wl17sehyRkZ6a/tFGii4CZyTOirClSiGsqp4hRTBNjE6saSxtl0+Z9WdJGLePw3r840PaheURw6f+47Gmait9fiY52htUfjnzAix4OlwXHqUSXdSVFiOBa+6a+fhCtfqVwfAPWX6XwdgYYRYFzAE2IAvBx2Yj/uXhXmns1pu8qfYWwRDOSr8k # This value was modified by the sealed-secrets pipeline
