environment: prod

redis_host: master.anna-prod-elascache-rep-group.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 7
  replicas: 1
    
secret:
  redis_pass: AgBDnDXr9tR96GX429NfBSWvm0F0PqzBOcMDe+8tNf77O1Y/QqA3Rt+CaEvWc3a9WT/EYUuCZNKaI2KDFZ7I0Yuu7rT8kKb6miQyTuIDBySvc/ndYyY23DEgse1CkkiU/vWEKJ1ZwaXyWc4PFeIhtSp0LufSPeXN7ZII/kSzA+fjZj4kSkrW+H6qPJU/9ZJsFzA3ZKVSDqhZLymOIaIqvirF0DdjSDpr3qa0++ZYlFfY4wgSS4UgaFcSgozff78S4SPlbFaZzqmCx+Hw3JJZnskbYZIafa20FzZsCRtQti8zYUqHgbUQ4VP3u+Vdd9FdQ99etYvojRrL/jrQkFTzj3jrTh2pK7oAOeTphlOwDNycO1hkkX5KS2nRhBgiIh9SN9Pjpf7woh0e7uodTX4ik2DeH4S8lKjCKfnQmhVxQGDQakFJH0PW7eBmOZ2UhFFtwiz+N4eCqj9jFgBzejw7Gvz3Rl0wX1X8m/3IZjXDq4MHh2495VMh6EuuKDYa9n+3qyQeP0yT6ITKNPs/lpn7AhhCpEqhwYWPuO5Ju/qJhXudwsHdp7H2h0TZ7y8lucbAYPEKWxuNnvNHpbIxET5PC+BiWbVCGymBMyKJ7zBxZnHd+RaE/YiQmGIUdkMAVNT7o9mVitjjqe37rpoJd2r3GL3OdS49NS62g40fG1tVOqD9/8eJw20LCpgWqzdVKgjwHIlLgNHhpbWJLyHCjxzTHle2tfDjgV/S4cBTl/Y1n95CE4yI6iPdN8RPb0+xjQhoaiw= # This value was modified by the sealed-secrets pipeline
