environment: prod

redis_host: master.anna-prod-elascache-rep-group.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 10
  replicas: 1
    
secret:
  redis_pass: AgB5gx25Qx6jvrlWwjcA2m9MH4wNjtyIJX9etvEA+FjJYT6hfW8ppebrU8cQn35bjAfzshCNNzXiog0fNWI6UoTGidaqqKfT4ERO/6XaLqnfpvW3cJ1Mj8LbWXt99C6ho1JFPykDcgK9RnqsIZbZQ/B0fRbW3hISeT98w8BddbQL43Zeep4PIDUBzVtGGccork+GlxztwSRBIh8558FdHCn1gQtYT3EZBHTxzCESU6Mk5/Y7HAjoGdPQ3Ee/6kCaQofKIDx24hEcok6MSknUIRnPaUuA1mAR+qjXpyWo8Gak9LRhA0Mif7eVesUuZmcFPDLjMbhiOtRLfsgej2eatTyUb32hQj/1ZvENlm6lpsXR59ED8pW5X/CfK/MuBQGpz5BJABwl2mdp6Gn/5zLUNUim4i5FCLWgqolk1YLMwe4FY2xakwvYK1SbyrsUbz9gM8z7KjOFyPc6zR6f6NIQy6r4ZROMrjJM4QL5UYvrvkId5Xz/QGa+9yHzJA9P0WEJPUyr9w/eEkwPNx/Rus+yLtdRFYp/ehQ376BS7yybY1N8LsumHUUEDbGjrF7eHjZ6/NNNNIula0v8F+1RVqburXKuRDFSF7Fw0Ddxg8ro20K9vGHDsHXE2B09nOtiCbIV5lfvSAr8r7Gx98NtCdEsnP5RC184/hYX/y0vpPCfek+b4R5zJVVGZ8mI9LNfigD8z/45TKzL85NIENsKZsi7mYDgrTo9D6d/JXwcg+4s0+LFolSfV1FKgM/jOBfZkMkzVXc= # This value was modified by the sealed-secrets pipeline
