environment: stage

redis_host: 

deployment:
  image:
    tag: 2
  replicas: 1
  labels:
    full-name: meme-web-backend-stage # This value was modified by the initial-setup python script

secret:
  redis_pass: AgDGNhAsHgr2FTMtX+wMJerxTKHvNmhgC3Y7SJV90Q0Yp2DsVziKRXF6nmv4HrPGrLvAagJuZsuGZ5+tDrM4cLQoN0QaqnYUmSNyY9NtSk1v+7TkDMvySnBSL810JgD3KGb2s/xP84pYky+DDGUj25KOYWGF5BKNdKW1mbQmkcAIs+XqSrTDEw7FSyIhGS0BXicjhX0w1GgPrtXK+gcG3vR7qZpI1/Klm5VLGvs4xHY3Lqm93BCNMxGnnsT/T44Nc9I5YRvLaBUMvoSzFvH9mYAfagCr4mUod9EMYnHdYlOZBZqWEDL6v/S3OOl7emz3hs9vSvbFGdZDQkDijapzfV5Q22K86CYdTFE0urEJERSsa+wsR3GhR4Xqq0MKWfN4lwv580I16qw8ytzUFcP145618SIZoklJmCDoEpTj8IzBey1ffhBqvr7Vdu+WcNilTognUhrH9vBpVMEU8WjB8Rnk+Np0opWpHunMK/keTA9CxarDmbSbr/8/V2MpE5dSHx45ZC09OrbH25sWY9xdnh2Vr0MpC6aV2EE4YCSETXTgfdZSeWw732jlSvSFOnkCPMqnlpgi+Fxzp6gsf7i5BBATjE9oQ24mA6cKoLS0giOHqHEkkXBaD/urYlwig8qKW5slMfdoVBNl2R+s1KKbcUhaDzd7PTVv3CQDx78RzT0Fau7B8HToYfo4v4kVBifeb1TvMVil6MFcq2H9x+QmZRgE8hJAqf2nbwhbOPIxLQ== # This value was modified by the sealed-secrets pipeline
