environment: prod

redis_host:

deployment:
  image:
    tag: 2
  replicas: 1
  labels:
    full-name: meme-web-backend-prod # This value was modified by the initial-setup python script
    
secret:
  redis_pass: AgB/MIFj7CLVPMtyyHFqiStZOkiY0VJmeHLy+J9dIaOcbqdCOKaRn6zZY5gPVr6bsPRmuXdWRzk7pnofMLzmXq6LZIbyzzYklbgJjLII8Ydk2x4+hvB4r7MBJqHauwi4hZOGZ8jhzPbsCoVmJN53//2vZ89yOJ5TP92vCdbYys0MRASza+yNoDdFnAl2Fl2Ul+ZPqtSlH7kk2vD0m+OT92Op9veUrGS59dBz+BV7Pu6bPMeERDE6eyjwnjuaXcTmUVEwP13i0Sk8toH+2YCvxrGwI0Ev2U6kTVaBOk/Ef7wlCKKb18pBpQQVKIa5c8K+gIM6+WBqjHaKZVPiuWdp6xxFUwwozjOoMgA0Z7EXMMFaqZaqjfdDZAOSuMhUs27ew9A+LbzN9S+oG55BPfdeW9UM0SITtZhIZ/mwANIZYqqAytZoaQz7AnACJoPcV85DkmBnyyQHtt7nFcsAjofch1eNU1oMwpaSGPkdg39vCOCFf67jdeTQ6QIn9OxwYTTStUBaB3yUP4+prMZNUdyyPXhTvuRGTRKdbZETEFwVw7hBd7gi54fvUGA1jlyblZ0+gJRP1ErYhzsm5IpmrwOprR1ptyKbJqe7hJm+OjxBaU+yJxQWn6K+oSJXWa6ckuV/q06H41VU1cjsjuWPgQBARY5G1N5ds0QrhmrK9l8TNCM33bZdOCx5cKeFzdY2PZ3jdDbZwyQpB3xqycEDTzbT3I0/x8Kpp1QDUpsw2IG/ # This value was modified by the sealed-secrets pipeline
