environment: dev
    
redis_host: 

deployment:
  image:  
    tag: 2
  replicas: 1
  labels:
    full-name: meme-web-backend-dev # This value was modified by the initial-setup python script

secret:
  redis_pass: AgCstlW2P2k/BdC4GZupGjxgMrGlJTjaSzlFSxx66B7lbKtphY47eVTpjfKY8oI19NywkVTNlSaQa+Jq0ExO6xrFPMVO4yClzbHTk2Ad5papXFzrJaQeUdmbyip3BTrGm1Wa6SNl0JipN5wVVwZcxweaMWSYIiGjV5+gS20prCWoJ/5ZVIGrcqJBTe7LN0HcZf0MrXhc5rfD4x4XzS/SFaBgGbGngd+G81ec8/yeUz+nBztxRyarwgg0fo5DlVFbSM8bjlRciEj5fXO3I4QkkVLPBTa6t2xCQ1FAGKex9pDbRkUoqsJO9Ce3CF0s5YdprgivjU1ABlg/MqYuunt/gziCBg7eI4pYjiJ4hE+0tNUbSFCnFk8+tW+0StCf9azVsf9iph5S4RrWewJRrttyJPdnSgGV/ZBlLimNDn0GQgqX8ZTAEi+lRXcZy3+bVGX82dfnCtMYOo2uG0ptJ0LmaGsb5WTr2rCKc0ChOLAsaOlERDMCRiLOaUr1fIKpAqyEdNEjFQmIb3b49LZw2suF4dmBGk8nGSgB1DK1w1eqmSIsKfT3EmYhTQXpo8C+5b0vyor6apu4P0IBZN395JYP93TNTQifGWKbVxBHrn0nV42j3PCAceywByFE15ememOr0f05mtkcj98GRmEgl4pcj+d0ISfF+1Q4esbFx9VYMf4jEeqXN/8F+B4ALlxDkgumETVPEfQzX20IAAPv8vILH+I2nVtzrExIuBFP/Fs= # This value was modified by the sealed-secrets pipeline