environment: stage

redis_host: master.meme-web-stage-elascache-rep-group.shelfr.use1.cache.amazonaws.com

deployment:
  image:
    tag: 1
  replicas: 1
  labels:
    full-name: meme-web-backend-stage # This value was modified by the initial-setup python script

secret:
  redis_pass: AgCXzLf7eryA5jk5FCPiPcwbpDhPj1QP1LXgnXM2GM8nudy3qVHJZvthRUJU2gWx+dTvJzOT7UGeeLpoToFZX8KQJrJsBiz9D7pH+ymwmmQJHj8DjflAp2h4krI+YWcz5rOgxJT0lmEXZF8RE1fDUyovfUyKP2jJvpbFv7pssUu9WioSxJbvddiZ/9hfWrABI+2GuFPe8vXL0vNPdmQEFGEsoD8SwETis7ePTtS8yyAQjYR118xmk61pwMi+lQ+bOI2L45tgtmhbh6dNlk95vztxRSXCrWNyELptDV1LNnuORtzIjF4iY+75m5P4fMovD78XYjZqZnm4Ki5qtlV2liftgq7qUZstWFcnLqBL9+r2wYVOcROZNx6jFJ+WKtGgTZU+45e5Of6cOf6peTCIfUQSId+nOyZXR460eekMHq49pwoq68yWueioH7fHHcbsb6KSow3u/deCwZWLfoUD4RR6d2xIQ6WT/eTLevOhGemDWGocyiI9pKpbMifIy74pirxZZUcDOEnYGiXVfX2oQwXn4TuiTt0ElZm7EFomicVSlZlQXEi5mrZCl1f3CUlsqyeVolzQPvDcS8rAnhFFqj1MF5AllJmCpDQt4DblP8ak+7xT2KvjpKinhVu8umEvMVCB9EzZYk3lpWp+Fc1mJDvvh7i0hB2eLI80bBPHF5LGm0ZieQa57sT/qCk2F+QnFFcc0fwppujiE8W4w5QXx3RAa0IvoXczR4f02N+N/g== # This value was modified by the sealed-secrets pipeline
