environment: dev
    
redis_host: master.anna-dev-elascache-rep-group.shelfr.use1.cache.amazonaws.com

deployment:
  image:  
    tag: 2
  replicas: 1
  labels:
    full-name: meme-web-backend-dev # This value was modified by the initial-setup python script

secret:
  redis_pass: AgC/bsVzchxBq5Dg7uBSnxXypGcTvwk+L+ExWjE1A5FRFeSBrim58K8BXBwTSJo8NUWIwTDtPsI7IdlA6qbHL95rffn4eaGbSPX/SUhW+ZfT819WH8ZMqeAq4P34Ao463mKwP8ZEi2mSUNN4cI74lhmu9ht7kINoqYKpRDQmsMJVI+e2aLGhFGA8eLvDfj15LPddJA+q3pbJWshbNG0EdpuQXBUyF0M9T9AsTFD/PwGJicZ3TCmecSo4pL/CEnyoX6tZwKmzJSGwpIrSu1bxfq+boKBGBEQOnJjsKbG7I/X5jTx0c2joswW8GUuvZUZx/ynI1GimxEmyG+BoM1iZjta6YyKko5poxvDaCZkO25LduJyqeG+rUbSvK24MaopfQYzoyD2G+qb0wZ+9S0VcSL2MdLu7Wuy8SPvE9M6YiM5i3oIVmrUVhhCKT/in1cXNJwGdrLOrO0yzLsMde2VIC3CF/5b6jTIRVbjwbx4Y1/sDpF0D5Zd4EUKiLoLBs5IPVDv0TKvmBrxI+/t4RbjerNhLsq3kEgmWr+CeIEvmW+kqNlad0y8TN3N/Pb+aYhfVmyEI/u96MCUhQmou0M+Hlgjmejlkhcl1nwt+pJFXbsgIc6qgNQSICJryIVuaqDUvysVRKUz/SsDPgVdyo1L28C1ZWVRywySk5KhddWHU+sR/qNHqTG2xIyE0AByJznRDGAuJyPV6sOX3zTEarcWqCHLeEfXkc8LpedKe29c= # This value was modified by the sealed-secrets pipeline