name: 01-Build & push Backstage image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backstage/my-backstage/**'

env:
  APP_NAME: backstage # This value was modified by the initial-setup python script

jobs:
  build-and-push:
    name: Build & push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Yarn install and build
        working-directory: backstage/my-backstage
        run: |
          # Make sure you are using Node.js version 18
          nvm install 18
          nvm use 18
          nvm alias default 18
          node --version
          
          # Make sure you are using Yarn version 1.22.19
          yarn set version 1.22.19
          yarn --version

          yarn install --frozen-lockfile

          # tsc outputs type definitions to dist-types/ in the repo root, which are then consumed by the build
          yarn tsc

          # Build the backend, which bundles it all up into the packages/backend/dist folder.
          # The configuration files here should match the one you use inside the Dockerfile below.
          yarn build:backend --config ../../app-config.production.yaml

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}
          tag: ${{ github.run_number }}
          registry: docker.io
          directory: backstage/my-backstage
          dockerfile: backstage/my-backstage/packages/backend/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


  update-helm-values:
    name: Update image tag for DEV environment
    # if: ${{ success() }}
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # We update the local repo with a pull just in case there have been any recent modifications
      - name: Update repo
        run: git pull

      - name: Update tag in values-dev.yaml
        run: |
          sed 's/tag:.*/tag: ${{github.run_number}}/g' helm/infra/backstage/values-custom.yaml > values-custom.temp
          mv values-custom.temp helm/infra/backstage/values-custom.yaml

      - name: Commit changes to GitHub
        run: |
          git config --global user.email "GitHubActions@Build&Deploy${{ env.APP_NAME }}Workflow.com"
          git config --global user.name "GitHub Actions - Build & Deploy ${{ env.APP_NAME }} Workflow"
          git add helm/infra/backstage/values-custom.yaml
          git commit -m "${{ env.APP_NAME }} image tag updated to ${{github.run_number}} by GitHub Actions"
          git push