name: Build & push my-app-backend image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'application-code/my-app/backend/**'

env:
  SYSTEM: my-app
  SERVICE: backend

jobs:
  build-and-push:
    name: Build & push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ env.SYSTEM }}-${{ env.SERVICE }}
          tag: ${{ github.run_number }}
          registry: docker.io
          directory: application-code/${{ env.SYSTEM }}/${{ env.SERVICE }}
          dockerfile: application-code/${{ env.SYSTEM }}/${{ env.SERVICE }}/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


  deploy-dev:
    name: Update image tag for dev environment
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # We update the local repo with a pull just in case there have been any recent modifications
      # - name: Update repo
      #   run: git pull
        # run: git pull origin main


      - name: Commit changes to GitHub
        run: |
          git pull
          git config --global user.email "GitHubActions@SealedSecretWorkflow.com"
          git config --global user.name "GitHub Actions - Sealed Secret Workflow"
          git add ./helm/my-app/frontend/values.yaml
          git commit -m "Frontend hosts URLs updated by GitHub Actions"
          git push
