environment: stage

deployment:
  image:  
    tag: 32
  replicas: 1
  labels:
    full-name: matesito-frontend-stage

configmap: 
  nginxConf: |-
      location /api {
          proxy_pass http://matesito-backend-stage-service:3000/;
      }